services:

  auth-api:
    build:
      context: ./auth-api
    ports:
      - 8000:8000
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=myfancysecret
    networks:
      - app-network

  users-api:
    build: ./users-api
    container_name: users-api
    ports:
      - 8083:8083
    networks:
      - app-network

  todos-api:
    build: ./todos-api
    container_name: todos-api
    ports:
      - 8082:8082
    environment:
      - REDIS_HOST=true-ladybird-25795.upstash.io
      - REDIS_PASSWORD="AWTDAAIjcDFkYTNjZmFhMThmNTc0NWIzOTJhZWJkNzIwZDhhNzlhZHAxMA
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - JWT_SECRET=myfancysecret
    networks:
      - app-network  
    

  log-message-processor:
    build: ./log-message-processor
    container_name: log-processor
    environment:
      - REDIS_HOST=true-ladybird-25795.upstash.io
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - REDIS_PASSWORD=AWTDAAIjcDFkYTNjZmFhMThmNTc0NWIzOTJhZWJkNzIwZDhhNzlhZHAxMA
    networks:
      - app-network  

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - auth-api
      - users-api
      - todos-api
    networks:
      - app-network 
