services:

  auth-api:
    build:
      context: ./auth-api
    ports:
      - "8000:8000"
    networks:
      - app-network

  users-api:
    build: ./users-api
    container_name: users-api
    ports:
      - 8083:8083
    networks:
      - app-network

  todos-api:
    build: ./todos-api
    container_name: todos-api
    ports: 
      - "8082:8082"
    networks:
      - app-network  
    

  log-message-processor:
    build: ./log-message-processor
    container_name: log-processor
    networks:
      - app-network  

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - auth-api
      - users-api
      - todos-api
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

