name: Build and Deploy frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - master
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      SERVICE_NAME: frontend
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      # Opcional: si prefieres no hardcodear las URLs, ponlas en tus Secrets
      VUE_APP_AUTH_API_ADDRESS: https://auth-api-production-10a5.up.railway.app
      VUE_APP_TODOS_API_ADDRESS: https://todos-api-production-30d6.up.railway.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ env.SERVICE_NAME }}
        run: |
          docker build \
            --build-arg VUE_APP_AUTH_API_ADDRESS=${{ env.VUE_APP_AUTH_API_ADDRESS }} \
            --build-arg VUE_APP_TODOS_API_ADDRESS=${{ env.VUE_APP_TODOS_API_ADDRESS }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG} \
            ./${{ env.SERVICE_NAME }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Redeploy ${{ env.SERVICE_NAME }} in Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          RAILWAY_TOKEN=$RAILWAY_TOKEN railway redeploy --service ${{ env.SERVICE_NAME }} --yes
