name: Build and Deploy users-api

on:
  push:
    paths:
      - 'users-api/**'
    branches:
      - master
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      SERVICE_NAME: users-api
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ env.SERVICE_NAME }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG} ./${{ env.SERVICE_NAME }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Redeploy ${{ env.SERVICE_NAME }} in Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          RAILWAY_TOKEN=$RAILWAY_TOKEN railway redeploy --service ${{ env.SERVICE_NAME }} --yes
